### ISSUE TITLE
Exception thrown "startIndex cannot be larger than length of string. (Parameter 'startIndex')"

### ISSUE THREAD

**Issue by dermotblairca** [RehanSaeed/Schema.NET#547]
### Describe the bug

The exception "startIndex cannot be larger than length of string. (Parameter 'startIndex')" is thrown sometimes when deserializing a Product.

### Steps to reproduce

The following unit test can be used to reproduce it:
```
 [Test]
public void GetSchemaOrgProduct_GetProductWithNestedOffer()
{
    // Arrange
    var pageContent = File.ReadAllText("C:/SchemaOrgTestPages/SchemaNetExample.json");
    string exceptionMessage = "";

    // Act
    try
    {
        var product = SchemaSerializer.DeserializeObject<Product>(pageContent);
    }
    catch(Exception ex)
    {
        exceptionMessage = ex.Message;
    }

    // Assert
    Assert.AreEqual("", exceptionMessage);
}
```
The contents of the SchemaNetExample.json file are:
```
{
	"@context": "http://schema.org",
	"sku": "",
	"mpn": "",
	"@type": "Product",
	"name": "Beko B5RCNA405HXB Frižider sa zamrzivačem - Tempo Tehnika",
	"image": "https://www.tempo-tehnika.rs/images/products/big/76433.png",
	"description": "FRIŽIDERI   Bruto i neto zapremina     Ukupna bruto zapremina 407   Total Volume (l) 355 L   Total Fresh Food &amp; Chill Com Tempo Tehnika",
	"brand": {
		"@type": "Brand",
		"name": "BEKO"
	},
	"offers": {
		"@type": "Offer",
		"price": "79990",
		"priceCurrency": "RSD",
		"priceValidUntil": "2023-02-22",
		"availability": "https://schema.org",
		"url": "https://www.tempo-tehnika.rs/artikal/beko-b5rcna405hxb-frizider-sa-zamrzivacem"
	},
	"review": {
		"@type": "Review",
		"reviewRating": {
			"@type": "Rating",
			"ratingValue": "4",
			"bestRating": "5"
		},
		"author": {
			"@type": "Organization",
			"name": "Tempo Tehnika"
		}
	},
	"aggregateRating": {
		"@type": "AggregateRating",
		"ratingValue": "88",
		"bestRating": "100",
		"ratingCount": "20"
	}
}
```
The stack trace of the exception is:
```
at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Schema.NET.EnumHelper.TryParseEnumFromSchemaUri(Type enumType, String value, Object& result)
   at Schema.NET.ValuesJsonConverter.TryProcessTokenAsType(Utf8JsonReader& reader, Type targetType, Object& value)
   at Schema.NET.ValuesJsonConverter.ProcessToken(Utf8JsonReader& reader, Type[] targetTypes, JsonSerializerOptions options)
   at Schema.NET.ValuesJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(JsonElement element, Type returnType, JsonSerializerOptions options)
   at Schema.NET.ValuesJsonConverter.ProcessToken(Utf8JsonReader& reader, Type[] targetTypes, JsonSerializerOptions options)
   at Schema.NET.ValuesJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Schema.NET.SchemaSerializer.DeserializeObject[T](String value)
```
I'm guessing this is because the availability field is not a valid enum. However the schema.org validator site does say this is valid: https://validator.schema.org/#url=https%3A%2F%2Fwww.tempo-tehnika.rs%2Fartikal%2Fbeko-b5rcna405hxb-frizider-sa-zamrzivacem

I'm not sure if this is a bug really or maybe it was intentional to throw an exception like this. Maybe the ideal scenario would be that it handles it gracefully and still returns the Product object (without an availability) if feasible.

Even though I have added a few minor bugs lately, this package is awesome! It has been really useful to me so I just wanted to say thanks so much for all of your work on this!

### Expected behaviour

Maybe this is expected behaviour but I guess the ideal scenario might be to catch it and still return the Product object if feasible. I'm not sure though.

### Schema objects

https://schema.org/Product

**Comment by Turnerj** [comment]
Yeah, that looks like a bug to me. Our code does a check if the value starts with `https://schema.org` and then attempts a substring of from `("https://schema.org".Length + 1)` which is invalid if the value is _only_ `https://schema.org` with no additional characters.

**Comment by Turnerj** [comment]
> Maybe the ideal scenario would be that it handles it gracefully and still returns the Product object (without an availability) if feasible.

Yeah, this is my thought too.

**Comment by dermotblairca** [comment]
Thanks very much for the quick reply and pull request!

**Comment by RehanSaeed** [comment]
PR merged. Release going out soon.
