### ISSUE TITLE
The JSON property name for 'Schema.NET.IHospital.OpeningHours' collides with another property.

### ISSUE THREAD

**Issue by fewless2019** [RehanSaeed/Schema.NET#603]
### Describe the bug

Can not serialize a schema.net.Physician while using schema.net.MedicalWebPage

Properties with the same name. 

hospital ->CivicStructureAndEmergencyServiceAndMedicalOrganization -> 
```csharp
[JsonPropertyName("openingHours")]
[JsonPropertyOrder(307)]
[JsonConverter(typeof(ValuesJsonConverter))]
public override OneOrMany<string> OpeningHours { get; set; }
```

Physician-> MedicalBusinessAndMedicalOrganization -> LocalBusinessAndOrganization -> 
```csharp
[JsonPropertyName("openingHours")]
[JsonPropertyOrder(238)]
[JsonConverter(typeof(ValuesJsonConverter))]
public OneOrMany<string> OpeningHours { get; set; }
```

### Steps to reproduce

```csharp
//Site Default
MedicalAudience medicalAudience = new MedicalAudience()
{
	RequiredMinAge = 0,
	RequiredMaxAge = 21,
	SuggestedMinAge = 0,
	SuggestedMaxAge = 21,
	SuggestedGender = "All genders"
};

MedicalWebPage website = new MedicalWebPage()
{
	MedicalAudience = medicalAudience
};


Physician physician = new Physician()
{
	Name = doctorProfilePage.DisplayName,
	Description = doctorProfilePage.CurrentPage.SeoSettings.Description,
};

if (Uri.IsWellFormedUriString(doctorProfilePage.Image, UriKind.Absolute))
{
	Uri outUri;

	if (Uri.TryCreate(doctorProfilePage.Image, UriKind.RelativeOrAbsolute, out outUri))
	{
		ImageObject image = new ImageObject()
		{
			ThumbnailUrl = outUri,
			Url = outUri
		};

		physician.Image = image;
		physician.Photo = image;
		website.Image = image;
	}
}

physician.Address = doctorProfilePage.GetSchemaAddress();
physician.Telephone = doctorProfilePage.GetSchemaPhone();
physician.Identifier = doctorProfilePage.ProfileId.ToString();
physician.Id = baseUri;
					
//website.MainEntity = mainHospital;
website.About = physician;

return website.ToHtmlEscapedString()  //Fails here. on ToHtmlEscapedString
```

**Stack trace**
``` 
System.InvalidOperationException: The JSON property name for 'Schema.NET.IHospital.OpeningHours' collides with another property.
at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(Type type, String propertyName) 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.AddProperty(JsonPropertyInfo jsonPropertyInfo, PropertyHierarchyResolutionState& state) 
at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean shouldCheckMembersForRequiredMemberAttribute, PropertyHierarchyResolutionState& state) 
at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo) 
at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options) 
at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options) 
at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type) 
at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context) 
--- End of stack trace from previous location --- 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.g__ConfigureSynchronized|161_0() 
at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo.g__ConfigureSynchronized|161_0() 
at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options) 
at Schema.NET.ValuesJsonConverter.WriteObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options) in /_/Source/Common/ValuesJsonConverter.cs:line 184
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state) 
at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer) 
at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state) 
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state) 
at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state) 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed, Boolean isInvokedByPolymorphicConverter) 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsObject(Utf8JsonWriter writer, Object rootValue, Boolean isInvokedByPolymorphicConverter) 
at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed, Boolean isInvokedByPolymorphicConverter) 
at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo) 
at Schema.NET.Thing.ToString() in /_/Source/Common/Thing.Partial.cs:line 23 
at SeattleChildrens.Features.SchemaExtensions.GenerateSchema(IHtmlHelper helper, IWebPage viewModel) in C:\repos\SeattleChildrens.orgCore\SeattleChildrens.Features\Infrastructure\Extensions\SchemaExtensions.cs:line 593
```

Properties with the same Name
hospital ->CivicStructureAndEmergencyServiceAndMedicalOrganization -> 
```csharp
[JsonPropertyName("openingHours")]
[JsonPropertyOrder(307)]
[JsonConverter(typeof(ValuesJsonConverter))]
public override OneOrMany<string> OpeningHours { get; set; }
```

Physician-> MedicalBusinessAndMedicalOrganization -> LocalBusinessAndOrganization -> 
```csharp
[JsonPropertyName("openingHours")]
[JsonPropertyOrder(238)]
[JsonConverter(typeof(ValuesJsonConverter))]
public OneOrMany<string> OpeningHours { get; set; }
```

### Expected behaviour

Unique names and ability to serialize. 

### Schema objects

schema.net.Physician
schema.net.MedicalWebPage

**Comment by fewless2019** [comment]
we are using .net 6

attattachedatched is the Json that produces the error.
I am a bit lost.

We use Schema.NET.MedicalWebPage
then we fill out the info for the Schema.NET.Physician nothing to do with the hospital. is even included when we go to serialize this.

how ever when i used Schema.NET.Person instead of Schema.NET.Physician it works fine.

Thanks,

David Fewless
Senior Web Developer, Diagram

[A close-up of a clock  Description automatically generated with medium confidence]
  e: ***@***.******@***.***>
  p: 630-491-2622
  w: www.wearediagram.com<http://www.wearediagram.com/>
  he/him
  [cid:c0afc9ac-d344-4d09-bfe9-33d4e05546a9] <https://twitter.com/wearediagram>   [cid:54944cde-315f-4968-a540-0571ae6566b1] <https://www.linkedin.com/company/19151275/admin/>   [cid:22682a1f-e095-42d0-991e-71db8b4a0d15] <https://www.instagram.com/heydiagram>


________________________________

**Comment by fewless2019** [comment]
We are using .Net6

Attached is the Json.

I fixed this by creating my own physician class and removing the hospital affiliation variable.


///// <summary>
///// A hospital with which the physician or office is affiliated.
///// </summary>
//[JsonPropertyName("hospitalAffiliation")]
//[JsonPropertyOrder(407)]
//[JsonConverter(typeof(ValuesJsonConverter))]
//public OneOrMany<IHospital> HospitalAffiliation { get; set; }

Thanks,

David Fewless
Senior Web Developer, Diagram

[A close-up of a clock  Description automatically generated with medium confidence]
  e: ***@***.******@***.***>
  p: 630-491-2622
  w: www.wearediagram.com<http://www.wearediagram.com/>
  he/him
  ***@***.*** <https://twitter.com/wearediagram>   ***@***.*** <https://www.linkedin.com/company/19151275/admin/>   ***@***.*** <https://www.instagram.com/heydiagram>

**Comment by kirk-marple** [comment]
Just ran across this issue, since I saw a similar issue serializing 'MedicalStudy'.

I'm getting this error:
The JSON property name for 'Schema.NET.IDrug.Funding' collides with another property.

This is using .NET 8.0 version of System.Text.Json.

**Comment by kirk-marple** [comment]
Looks like my serialization issue was due to 'Drug' being a subclass of both Product and Substance, and the 'Funding' property is defined in both places.

Not sure how Schema.NET is supposed to handle these kinds of situations?

I had to create a private version of the library, and remove 'Product' from the JSON-LD file to get it working.

cc: @Turnerj @RehanSaeed

**Comment by yisraelg3** [comment]
I am having the same issue as @fewless2019 with the `OpeningHours` properties between the Physician and Hospital classes colliding.

I just upgraded to .NET 8 and Schema.NET 13.0.0, and that's when this issue started.
I was **not** having this issue when I was using .NET 6

According to my understanding this might be caused by the new serialization improvements made in .NET 8, in particular the improvements for [Interface hierarchy support](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#interface-hierarchy-support).

In order to fix the error I had to copy the entire `Physician` class and copy it to a local `ModifiedPhysician` class and remove the `HospitalAffiliation` property (which we aren't using). That resolved our issue.

**Comment by fewless2019** [comment]
@yisraelg3 Yea that was my fix for this as well, I extended the schema classes for what I needed instead of using the base classes in Schema.

**Comment by yisraelg3** [comment]
You do what you got to do.
It would be nice if Schema.Net would add support for this at some point.

**Comment by andres-hernandez-verndale** [comment]
@fewless2019 @yisraelg3 could you please provide an example of the custom class you created?

**Comment by fewless2019** [comment]
@andres-hernandez-verndale 

Take a look at the Schema.Net.Physician type.  https://schema.org/Physician

`public partial class Physician : MedicalBusinessAndMedicalOrganization, IPhysician, IEquatable<Physician>
{
    /// <summary>
    /// Gets the name of the type as specified by schema.org.
    /// </summary>
    [JsonPropertyName("@type")]
    [JsonPropertyOrder(1)]
    public override string Type => "Physician";

    /// <summary>
    /// A medical service available from this provider.
    /// </summary>
    [JsonPropertyName("availableService")]
    [JsonPropertyOrder(406)]
    [JsonConverter(typeof(ValuesJsonConverter))]
    public Values<IMedicalProcedure, IMedicalTest, IMedicalTherapy> AvailableService { get; set; }

    /// <summary>
    /// A hospital with which the physician or office is affiliated.
    /// </summary>
    [JsonPropertyName("hospitalAffiliation")]
    [JsonPropertyOrder(407)]
    [JsonConverter(typeof(ValuesJsonConverter))]
    public OneOrMany<IHospital> HospitalAffiliation { get; set; }

    /// <summary>
    /// A medical specialty of the provider.
    /// </summary>
    [JsonPropertyName("medicalSpecialty")]
    [JsonPropertyOrder(408)]
    [JsonConverter(typeof(ValuesJsonConverter))]
    public override OneOrMany<MedicalSpecialty?> MedicalSpecialty { get; set; }`

I took that an added it to my custom class along with the other types i needed but commented out  HospitalAffiliation. 

my customPhysician class 
`	using Schema.NET;
	using System.Text.Json.Serialization;

	public class CustomPhysician : IThing
	{
		/// <summary>
		/// The name of the item.
		/// </summary>
		[JsonPropertyName("name")]
		[JsonPropertyOrder(4)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public OneOrMany<string> Name { get; set; }

		/// <summary>
		/// A description of the item.
		/// </summary>
		[JsonPropertyName("description")]
		[JsonPropertyOrder(5)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public OneOrMany<string> Description { get; set; }
		/// <summary>
		/// Gets the name of the type as specified by schema.org.
		/// </summary>
		[JsonPropertyName("@type")]
		[JsonPropertyOrder(1)]
		public string Type => "Physician";

		/// <summary>
		/// A medical service available from this provider.
		/// </summary>
		[JsonPropertyName("availableService")]
		[JsonPropertyOrder(406)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public Values<IMedicalProcedure, IMedicalTest, IMedicalTherapy> AvailableService { get; set; }

		///// <summary>
		///// A hospital with which the physician or office is affiliated.
		///// </summary>
		//[JsonPropertyName("hospitalAffiliation")]
		//[JsonPropertyOrder(407)]
		//[JsonConverter(typeof(ValuesJsonConverter))]
		//public OneOrMany<IHospital> HospitalAffiliation { get; set; }

		/// <summary>
		/// A medical specialty of the provider.
		/// </summary>
		[JsonPropertyName("medicalSpecialty")]
		[JsonPropertyOrder(408)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public OneOrMany<MedicalSpecialty?> MedicalSpecialty { get; set; }

		[JsonPropertyName("image")]
		[JsonPropertyOrder(11)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public Values<IImageObject, Uri> Image { get; set; }

		/// <summary>
		/// A photograph of this place.
		/// </summary>
		[JsonPropertyName("photo")]
		[JsonPropertyOrder(161)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public virtual Values<IImageObject, IPhotograph> Photo { get; set; }

		/// <summary>
		/// Physical address of the item.
		/// </summary>
		[JsonPropertyName("address")]
		[JsonPropertyOrder(206)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public Values<IPostalAddress, string> Address { get; set; }

		/// <summary>
		/// The telephone number.
		/// </summary>
		[JsonPropertyName("telephone")]
		[JsonPropertyOrder(250)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public OneOrMany<string> Telephone { get; set; }

		/// <summary>
		/// The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
		/// </summary>
		[JsonPropertyName("identifier")]
		[JsonPropertyOrder(10)]
		[JsonConverter(typeof(ValuesJsonConverter))]
		public Values<IPropertyValue, string, Uri> Identifier { get; set; }

		/// <summary>
		/// Gets or sets the identifier used to uniquely identify things that are being described in the document with
		/// IRIs or blank node identifiers.
		/// To be able to externally reference nodes in a graph, it is important that nodes have an identifier. IRIs
		/// are a fundamental concept of Linked Data, for nodes to be truly linked, dereferencing the identifier should
		/// result in a representation of that node.This may allow an application to retrieve further information about
		/// a node. In JSON-LD, a node is identified using the @id keyword:
		/// </summary>
		[JsonPropertyName("@id")]
		[JsonPropertyOrder(2)]
		public virtual Uri? Id { get; set; }


		public OneOrMany<Uri> AdditionalType { get; set; }
		public OneOrMany<string> AlternateName { get; set; }
		public OneOrMany<string> DisambiguatingDescription { get; set; }
		public Values<ICreativeWork, Uri> MainEntityOfPage { get; set; }
		public OneOrMany<IAction> PotentialAction { get; set; }
		public OneOrMany<Uri> SameAs { get; set; }
		public Values<ICreativeWork, IEvent> SubjectOf { get; set; }
		public OneOrMany<Uri> Url { get; set; }
		Values<string, ITextObject> IThing.Description { get; set; }
		Values<string, Uri> IThing.AdditionalType { get; set; }
		public OneOrMany<IPropertyValue> AdditionalProperty { get; set; }
	}`

**Comment by andres-hernandez-verndale** [comment]
thank you @fewless2019!
