### ISSUE TITLE
Can't deserialize response from NHS Search which says it complies with schema.org

### ISSUE THREAD

**Issue by horizondave** [RehanSaeed/Schema.NET#91]
```
            var content = response.Content;
            var srp = JsonConvert.DeserializeObject<Schema.NET.SearchResultsPage>(content);

```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error setting value to 'Breadcrumb' on 'Schema.NET.SearchResultsPage'.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   
### To Reproduce
Register for API access at https://developer.api.nhs.uk/documentation/content-api?filter=news
Call the "Behind The Headline" /  "All News" API
Try to deserialize the result as above.
(or do the same with the sample response attached)

### Expected behaviour

The response should deserialize correctly without an error.

### Schema Objects

SearchResultPage

[ExampleBehindTheHeadlinesResponse.txt](https://github.com/RehanSaeed/Schema.NET/files/3755632/ExampleBehindTheHeadlinesResponse.txt)

**Comment by RehanSaeed** [comment]
Can you try the latest version either by cloning this repo or getting it from [GitHub packages](https://github.com/RehanSaeed/Schema.NET/packages/27403)? There have been some fairly large changes that may or may not fix this issue.

**Comment by horizondave** [comment]
I won't get chance to try this again until Monday at the earliest, sorry.

**Comment by Turnerj** [comment]
I've had a look into this with the latest build of Schema.NET and while there are no errors, there are some issues with the response data from the API you're referring to (using your attached response).

`interactionStatistic.interactionService.url` is set as `<img style='border: 0; width: 1px; height: 1px;' alt='' src='https://statse.webtrendslive.com/dcs2221tai1ckz5huxw0mfq86_1m2w/njs.gif?dcsuri=news/?order=newest&page=1&wt.cg_n=Syndication&wt.cg_s=News&synduserid=170da830-e5f5-11e9-b821-6d2c470f88f4&syndreviewdate=22-10-2019T10:28'/> <img style='border: 0; width: 1px; height: 1px;' alt='' src='https://nhsdigital.d3.sc.omtrdc.net/b/ss/nhsuk-prod/1/JS-2.9.0-L8UK/654321?c27=170da830-e5f5-11e9-b821-6d2c470f88f4&c28=news/?order=newest&page=1&c29=News&c75=web&events=event23'/>` however that is not a valid URI and won't be parsed.

[`significantLink`](https://schema.org/significantLink) should only be URIs however the example you gave uses [`LinkRole`](https://schema.org/LinkRole) which [is currently pending](https://github.com/schemaorg/schemaorg/issues/1045).

Besides those two points, everything else seemed to parse correctly.

**Comment by RehanSaeed** [comment]
Thanks for taking a look @Turnerj.

@horizondave Please feel free to reopen if there is anything more to add.
